name: data-pipeline-workflow

supabase:
  url: "https://thxvfnachnpgmeottlem.supabase.co"
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  bucket: "apsbucket"

on: 
  push:
  workflow_dispatch:
  schedule:
      - cron: '0 */4 * * *'

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Show current time
        run: date
        
      - name: Checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data pipeline
        run: python data_pipeline.py

      - name: Check for changes
        id: git-check
        run: |
          git config user.name 'apspayments'
          git config user.email 'aps@aps.business'
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push if changes
        if: env.changes == 'true'
        run: |
          git commit -m "Automated update from data pipeline"
          git push
